name: download_task
description: Resumable http download request
version: 1.0.0
repository: https://github.com/starkdmi/resumable_download

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  http: ^0.13.4

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0